# Generated by Django 4.0.2 on 2022-05-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_casa', models.IntegerField(max_length=8)),
                ('id_condominio', models.IntegerField(max_length=8)),
                ('descripcion', models.CharField(max_length=200)),
                ('saldo', models.IntegerField(max_length=8)),
                ('luz', models.IntegerField(max_length=8)),
                ('agua', models.IntegerField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_condominio', models.IntegerField(max_length=8)),
                ('nombre_condominio', models.CharField(max_length=200)),
                ('num_casas', models.IntegerField(max_length=8)),
                ('num_casas_ocupadas', models.IntegerField(max_length=8)),
                ('mantencion', models.IntegerField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Espacios_comunes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_espacio', models.IntegerField(max_length=8)),
                ('id_condominio', models.IntegerField(max_length=8)),
                ('tipo_espacio', models.CharField(max_length=50)),
                ('costo_arriendo', models.IntegerField(max_length=8)),
                ('mantencion', models.IntegerField(max_length=8)),
                ('aforo', models.IntegerField(max_length=8)),
                ('ocupado', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Seguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo_usuario', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10)),
                ('nombres', models.CharField(max_length=50)),
                ('apellido1', models.CharField(max_length=50)),
                ('apellido2', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('telefono', models.IntegerField(max_length=10)),
                ('casa', models.IntegerField(max_length=8)),
                ('condominio', models.IntegerField(max_length=8)),
                ('directiva', models.CharField(max_length=2)),
                ('conserje', models.CharField(max_length=2)),
                ('horario', models.CharField(max_length=100)),
                ('fecha_ingreso', models.CharField(max_length=50)),
            ],
        ),
    ]
