# Generated by Django 4.0.2 on 2022-05-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCondominio', '0002_remove_casa_agua_remove_casa_id_casa_remove_casa_luz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='agua',
            field=models.IntegerField(default=0, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casa',
            name='id_casa',
            field=models.IntegerField(default=0, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casa',
            name='luz',
            field=models.IntegerField(default=0, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casa',
            name='saldo',
            field=models.IntegerField(default=0, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='condominio',
            name='id_condominio',
            field=models.IntegerField(default=0, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='condominio',
            name='mantencion',
            field=models.IntegerField(default=0, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='condominio',
            name='num_casas',
            field=models.IntegerField(default=0, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='condominio',
            name='num_casas_ocupadas',
            field=models.IntegerField(default=0, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='espacios_comunes',
            name='aforo',
            field=models.IntegerField(default=0, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='espacios_comunes',
            name='costo_arriendo',
            field=models.IntegerField(default=0, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='espacios_comunes',
            name='id_condominio',
            field=models.IntegerField(default=0, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='espacios_comunes',
            name='id_espacio',
            field=models.IntegerField(default=0, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='espacios_comunes',
            name='mantencion',
            field=models.IntegerField(default=0, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seguridad',
            name='habilitado',
            field=models.IntegerField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='casa',
            field=models.IntegerField(default=0, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='habilitado',
            field=models.IntegerField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.IntegerField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
