# Generated by Django 4.0.2 on 2022-05-24 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCondominio', '0003_casa_agua_casa_id_casa_casa_luz_casa_saldo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casa',
            name='id_casa',
        ),
        migrations.RemoveField(
            model_name='condominio',
            name='id_condominio',
        ),
        migrations.RemoveField(
            model_name='espacios_comunes',
            name='id_espacio',
        ),
    ]
